### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by aimarjs** [RiskIdent/terraform-provider-mongodb-driver#24]
Hello,

It's a great provider, but I found a bug in it.
If I have more than one role that needs to be attached to the user, it will fail with the following error.

If i have a user map as follows

<img width="502" alt="image" src="https://github.com/RiskIdent/terraform-provider-mongodb-driver/assets/25065245/395f2953-4fd4-4b3b-865f-cd5ffe25c485">

And try to add it as follows.

<img width="515" alt="image" src="https://github.com/RiskIdent/terraform-provider-mongodb-driver/assets/25065245/90051bc4-0001-4063-a5e8-5e60da737972">

Only the first role will be added, and then an error will be thrown

`
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.mongodb.mongodb_user.sa_user["user_name"], provider
│ "module.mongodb.provider[\"registry.terraform.io/riskident/mongodb-driver\"].mongodb-driver" produced an unexpected new
│ value: .roles: element 2 has vanished.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
`

**Comment by applejag** [comment]
Hello @aimarjs ! Thanks for the bug report!

What version of the provider are you using? We recently made some changes in the roles recently in v0.1.2 (released 2 weeks ago)

We'll tack this in our backlog in our internal issue tracker. Do warn that we're a bit swamped right now with tasks, so if you have time and energy to debug and develop a fix, then we'd be happy to review it :)

**Comment by aimarjs** [comment]
hey @applejag. I was using 0.1.1. I did the upgrade to 0.1.2, and now the provider will crash.

`
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-mongodb-driver_v0.1.2 plugin:

panic: interface conversion: interface is nil, not bsoncodec.ValueEncoder

goroutine 9 [running]:
go.mongodb.org/mongo-driver/bson/bsoncodec.(*typeEncoderCache).LoadOrStore(...)
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/codec_cache.go:45
go.mongodb.org/mongo-driver/bson/bsoncodec.(*Registry).storeTypeEncoder(0x140001f8a10?, {0x102edbea8?, 0x102dbc0c0?}, {0x0, 0x0})
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/registry.go:416 +0x80
go.mongodb.org/mongo-driver/bson/bsoncodec.(*Registry).LookupEncoder(0x140001f8a10, {0x102edbea8, 0x102dbc0c0})
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/registry.go:411 +0x1fc
go.mongodb.org/mongo-driver/bson/bsoncodec.SliceCodec.EncodeValue({0xd8?}, {0x140001f8a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/slice_codec.go:89 +0x2ac
go.mongodb.org/mongo-driver/bson/bsoncodec.(*StructCodec).EncodeValue(0x1400013d280, {0x140001f8a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/struct_codec.go:222 +0x4f8
go.mongodb.org/mongo-driver/bson.(*Encoder).Encode(0x140005183c0, {0x102e56240, 0x14000480600})
        go.mongodb.org/mongo-driver@v1.13.0/bson/encoder.go:119 +0x1f4
go.mongodb.org/mongo-driver/mongo.marshal({0x102e56240?, 0x14000480600?}, 0x94?, 0x102b4a57b?)
        go.mongodb.org/mongo-driver@v1.13.0/mongo/mongo.go:171 +0xfc
go.mongodb.org/mongo-driver/mongo.(*Database).processRunCommand(0x140004805a0, {0x102ecff00?, 0x140001da070?}, {0x102e56240, 0x14000480600}, 0x0, {0x0, 0x0, 0x14000806048?})
        go.mongodb.org/mongo-driver@v1.13.0/mongo/database.go:164 +0x280
go.mongodb.org/mongo-driver/mongo.(*Database).RunCommand(0x140004805a0, {0x102ecff00?, 0x140001da070?}, {0x102e56240?, 0x14000480600?}, {0x0?, 0x0?, 0x1400073e818?})
        go.mongodb.org/mongo-driver@v1.13.0/mongo/database.go:215 +0x78
github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb.(*Client).runUpdateUser(0x14000522600?, {0x102ecff00, 0x140001da070}, {0x1400034e220?, 0x140005fe8d8?}, {{0x140005da180, 0x26}, {0x140003a8280, 0x1e}, 0x140006306f0, ...})
        github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb/mongodb.go:307 +0xac
github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb.(*Client).UpdateDBUser(0x0?, {0x102ecff00, 0x140001da070}, {0x1400034e220, 0x5}, {{0x140005da180, 0x26}, {0x140003a8280, 0x1e}, 0x140006306f0, ...})
        github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb/mongodb.go:294 +0xc8
github.com/RiskIdent/terraform-provider-mongodb-driver/internal/provider.(*UserResource).Update(0x140003c8038, {0x102ecfe58, 0x14000451ad0}, {{{{0x102ed45f0, 0x14000591b30}, {0x102da9500, 0x140005909c0}}, {0x102ed6510, 0x1400040c280}}, {{{0x102ed45f0, ...}, ...}, ...}, ...}, ...)
        github.com/RiskIdent/terraform-provider-mongodb-driver/internal/provider/user_resource.go:373 +0x614
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).UpdateResource(0x140001a6f20, {0x102ecfe58, 0x14000451ad0}, 0x1400073f370, 0x1400073f280)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_updateresource.go:122 +0x564
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x140004db490?, {0x102ecfe58, 0x14000451ad0}, 0x1400057edc0, 0x1400073f490)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_applyresourcechange.go:102 +0x118
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140001a6f20, {0x102ecfe58?, 0x140004519b0?}, 0x1400057ed20)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_applyresourcechange.go:55 +0x314
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x1400022c8c0, {0x102ecfe58?, 0x140004511d0?}, 0x140001f8000)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x102e8dbe0?, 0x1400022c8c0}, {0x102ecfe58, 0x140004511d0}, 0x1400079e180, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001ec1e0, {0x102ecfe58, 0x14000451140}, {0x102ed51d8, 0x1400033cd00}, 0x140003d9200, 0x1400033a4e0, 0x10345a638, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140001ec1e0, {0x102ed51d8, 0x1400033cd00}, 0x140003d9200)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0x988
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 28
        google.golang.org/grpc@v1.59.0/server.go:997 +0x160
panic: interface conversion: interface is nil, not bsoncodec.ValueEncoder

goroutine 55 [running]:
go.mongodb.org/mongo-driver/bson/bsoncodec.(*typeEncoderCache).LoadOrStore(...)
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/codec_cache.go:45
go.mongodb.org/mongo-driver/bson/bsoncodec.(*Registry).storeTypeEncoder(0x140001f8a10?, {0x102edbea8?, 0x102dbc0c0?}, {0x0, 0x0})
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/registry.go:416 +0x80
go.mongodb.org/mongo-driver/bson/bsoncodec.(*Registry).LookupEncoder(0x140001f8a10, {0x102edbea8, 0x102dbc0c0})
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/registry.go:411 +0x1fc
go.mongodb.org/mongo-driver/bson/bsoncodec.SliceCodec.EncodeValue({0xe8?}, {0x140001f8a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/slice_codec.go:89 +0x2ac
go.mongodb.org/mongo-driver/bson/bsoncodec.(*StructCodec).EncodeValue(0x1400013d280, {0x140001f8a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
        go.mongodb.org/mongo-driver@v1.13.0/bson/bsoncodec/struct_codec.go:222 +0x4f8
go.mongodb.org/mongo-driver/bson.(*Encoder).Encode(0x140000a9080, {0x102de3d60, 0x14000818a20})
        go.mongodb.org/mongo-driver@v1.13.0/bson/encoder.go:119 +0x1f4
go.mongodb.org/mongo-driver/mongo.marshal({0x102de3d60?, 0x14000818a20?}, 0x0?, 0x0?)
        go.mongodb.org/mongo-driver@v1.13.0/mongo/mongo.go:171 +0xfc
go.mongodb.org/mongo-driver/mongo.(*Database).processRunCommand(0x140008189c0, {0x102ecff00?, 0x140001da2a0?}, {0x102de3d60, 0x14000818a20}, 0x0, {0x0, 0x0, 0x140003a6668?})
        go.mongodb.org/mongo-driver@v1.13.0/mongo/database.go:164 +0x280
go.mongodb.org/mongo-driver/mongo.(*Database).RunCommand(0x140008189c0, {0x102ecff00?, 0x140001da2a0?}, {0x102de3d60?, 0x14000818a20?}, {0x0?, 0x33b0dcad61fa9?, 0x0?})
        go.mongodb.org/mongo-driver@v1.13.0/mongo/database.go:215 +0x78
github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb.(*Client).runCreateUser(0x14000522600?, {0x102ecff00, 0x140001da2a0}, {0x140005d8060?, 0x14000560948?}, {{0x1400003c198, 0x15}, {0x14000594000, 0x1e}, 0x140000ec8a0, ...})
        github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb/mongodb.go:268 +0x100
github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb.(*Client).CreateDBUser(0x0?, {0x102ecff00, 0x140001da2a0}, {0x140005d8060, 0x5}, {{0x1400003c198, 0x15}, {0x14000594000, 0x1e}, 0x140000ec8a0, ...})
        github.com/RiskIdent/terraform-provider-mongodb-driver/internal/mongodb/mongodb.go:242 +0xc8
github.com/RiskIdent/terraform-provider-mongodb-driver/internal/provider.(*UserResource).Create(0x1400020e000, {0x102ecfe58, 0x140006c40f0}, {{{{0x102ed45f0, 0x140005b46f0}, {0x102da9500, 0x140006c5740}}, {0x102ed6510, 0x1400040c280}}, {{{0x102ed45f0, ...}, ...}, ...}, ...}, ...)
        github.com/RiskIdent/terraform-provider-mongodb-driver/internal/provider/user_resource.go:293 +0x614
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140001a6f20, {0x102ecfe58, 0x140006c40f0}, 0x14000733330, 0x140007332d0)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:101 +0x41c
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x1400064f490?, {0x102ecfe58, 0x140006c40f0}, 0x140006d6960, 0x14000733490)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_applyresourcechange.go:57 +0x380
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140001a6f20, {0x102ecfe58?, 0x140005e1fb0?}, 0x140006d68c0)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_applyresourcechange.go:55 +0x314
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x1400022c8c0, {0x102ecfe58?, 0x140005e17a0?}, 0x14000220000)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x102e8dbe0?, 0x1400022c8c0}, {0x102ecfe58, 0x140005e17a0}, 0x14000428600, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001ec1e0, {0x102ecfe58, 0x140005e1080}, {0x102ed51d8, 0x1400033cd00}, 0x14000015e60, 0x1400033a4e0, 0x10345a638, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140001ec1e0, {0x102ed51d8, 0x1400033cd00}, 0x14000015e60)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0x988
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 28
        google.golang.org/grpc@v1.59.0/server.go:997 +0x160

Error: The terraform-provider-mongodb-driver_v0.1.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`

**Comment by aimarjs** [comment]
Aah, 0.1.3 is the latest. Will try it now :)

**Comment by aimarjs** [comment]
Works like a charm @applejag. Cheers!
